### ISSUE TITLE
Sync submission status set in Kaznet

### ISSUE THREAD

**Issue by moshthepitt** [onaio/kaznet-web#270]
When auto-reviewing submissions in Kaznet, make sure the SubmissionReview is synced with Onadata

**Comment by moshthepitt** [comment]
Fixed in https://github.com/onaio/kaznet-frontend/pull/223

**Comment by moshthepitt** [comment]
Actually not fixed

**Comment by FrankApiyo** [comment]
**I'll add a method in ona/api.py that will do the following:**

- receive a submission created by task_create_submission(so its called by a different task started by this task)

- first check if the submission review has been synced with onadata already from it's json field and if not already synced, then  call onadata endpoint with the review status as arguments and the instance id in a POST request
