### ISSUE TITLE
Users can't connect a task to a form

### ISSUE THREAD

**Issue by faith-mutua** [onaio/kaznet-web#319]
**Expected behavior**

Admins should be able to connect tasks on the Kaznet web app to forms in the Kaznet org account on kaznet.ona.io. 

**Actual Behavior**
Admins are unable to connect/link tasks on the Kaznet web app to forms in kaznet.ona.io. The following error is returned when one tries to do so

```This form may not appear correctly in the Kaznet mobile app. Additionally, it may not be possible to submit data to this form. Please click this link to fix this form. You can fix it be ensuring that:```

```1. The form belongs to the right organisation```
```2. The form exists in a project which allows its members to make form submissions```

**Steps to reproduce**
1. Create a new task on the kaznet web app.
2. Try connecting the task to a form

**Comment by moshthepitt** [comment]
This is caused by #319

**Comment by FrankApiyo** [comment]
Since #322  was already fixed, this issue was fixed to ergo it should be closed.
