### ISSUE TITLE
Ensure user statistics are accurate

### ISSUE THREAD

**Issue by moshthepitt** [onaio/kaznet-web#328]
The `UserProfileSerializer` class contains a number of fields/properties that are reportedly not working and/or not kept in sync.  These include:

- gender and gender_display
- national_id
- email
- avg_amount_earned
- avg_approval_rate
- avg_rejected_submissions
- avg_approved_submissions
- avg_submissions
- approved_submissions
- rejected_submissions
- payment_number

We need to create something like an integration test that takes a new user and ensures that the values for the above fields are changed when the source data changes, and that they are always in sync.

**Comment by FrankApiyo** [comment]
I'll break down the tests required here into 3 PRs:

- [ ] First, tests for all properties of the UserProfile model

- [ ] Tests for the UserProfileSerializer for the properties of UserProfile listed above in the issue

- [ ] Tests for the UserPrifileViewSet for the properties of UserProfile listed above in the issue

These last two tests will ensure that changes to UserProfile model are reflected in both the serializer and the view set
