### ISSUE TITLE
Newly created users are not saved

### ISSUE THREAD

**Issue by faith-mutua** [onaio/kaznet-web#338]
**Environment**
https://kaznet-stage.onalabs.org

**Expected behavior**

Newly created users and all their details should be saved in the **Users** tab.

**Actual behavior**

Newly created users are not being saved under the **Users** tab. Some of their details are also not being saved such as ID.

**Steps to reproduce**
- Create a new user in the Kaznet web app https://kaznet-stage.onalabs.org

**Comment by FrankApiyo** [comment]
This is a kaznet-frontend bug. It'll be fixed there.

**Comment by moshthepitt** [comment]
> This is a kaznet-frontend bug. It'll be fixed there.

@FrankApiyo is there an issue that provides details on this bug?

**Comment by FrankApiyo** [comment]
> > This is a kaznet-frontend bug. It'll be fixed there.
> 
> @FrankApiyo is there an issue that provides details on this bug?

I'm currently working on this PR: https://github.com/onaio/kaznet-frontend/pull/258, it addresses this issue
