### ISSUE TITLE
Get form version from `.xml`  onadata endpoint instead of `.json` endpoint

### ISSUE THREAD

**Issue by FrankApiyo** [onaio/kaznet-web#346]
Implement a way to get form versions from the `.xml` endpoint for forms instead of the `.json` endpoint. Currently the form version field is gotten from this onadata endpoint: `'api/v1/forms/{xform_id}'`. This could be different for some reasons such as when a user explicitly sets their own form `version` field in the settings worksheet of their xls form.

**Comment by FrankApiyo** [comment]
To get the correct/most recent form version, I'm going to change the ` process_xform(xform_data: dict, project_id: int = None):` function in `ona.api.py` module such that before getting the form version this way :point_right: `version = xform_data.get('version')`, first it checks to see if the array value of the `form_versions` field of the *json* gotten from *onadata*  has any elements. if it does have elements then the version field of the first element will be taken as the correct *form version*. otherwise, we will proceed as usual and get the form version this way: `version = xform_data.get('version')`. 

We are going to attempt to get the correct form version from the `form_versions` property returns from the `/api/v1/forms/{form_id}` endpoint because it seems to always have the up to date version of the form.

The first element of the value of the `form_verions` property(this property is an array) will be used because it seems to be the most up to date `form_version`

**Comment by FrankApiyo** [comment]
a form version field looks like this: 
`
[
        {
            "version": "201911081134",
            "total": 22
        },
        {
            "version": "201910172011",
            "total": 18
        }
    ],
`

**Comment by FrankApiyo** [comment]
> Implement a way to get form versions from the `.xml` endpoint for forms instead of the `.json` endpoint. Currently the form version field is gotten from this onadata endpoint: `'api/v1/forms/{xform_id}'`. This could be different for some reasons such as when a user explicitly sets their own form `version` field in the settings worksheet of their xls form.

the `form_versions` field will always contain the latest `form_version`. so there may be no need to get data from the `.xml` endponit.

**Comment by ukanga** [comment]
The `form_versions` gets data from the submissions to the form , see [get_form_versions()](https://github.com/onaio/onadata/blob/8952fdb4f91186394c6182eb414bcb97e1a43cd1/onadata/libs/serializers/xform_serializer.py#L330) function. The version is going to be only based on submissions that have been received. There is no guarantee that the version displayed there is the latest version.

**Comment by ukanga** [comment]
You could also implement this functionality on the onadata side, perhaps `/api/v1/forms/[pk]/xform_version` that would extract the xform version from the XML content — no need for kaznet to download the XForm.

The reason the `version` field is not ideal is that we are not yet enforcing clients to define the form version according to the XForm specs. When we close the PR https://github.com/onaio/onadata/pull/989, perhaps then we can rely on the property value of `version`.

**Comment by FrankApiyo** [comment]
I think implementing this endpoint on `onadata` would be better than  be better than trying to extract the version from `XForm`.

**Comment by FrankApiyo** [comment]
Since there's already a `.json` API endpoint that returns the form version here :point_right:  https://github.com/onaio/onadata/issues/1721#issuecomment-556115571, I'm going to make a call to `/api/v1/forms/[pk]/form.json.` in order to get the form version. in stead of the `api/v1/forms/{xform_id}'` endpoint.

**Comment by FrankApiyo** [comment]
**work plan**
 

- [ ] Add a new function called `get_xform_version` that returns the *version* of an xform given it's *formid*

- [ ] call this function every time the form version is required.

**Comment by ukanga** [comment]
Sounds like a good plan.
